// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	MarketTypeID string `json:"marketTypeID"`
}

func (Game) IsEntity() {}

type Query struct {
}
