package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"customer-subgraph/graph/model"
	"customer-subgraph/resolvers/entities"
	"customer-subgraph/resolvers/queries"
)

// Transactions is the resolver for the transactions field.
func (r *customerResolver) Transactions(ctx context.Context, obj *model.Customer) ([]*model.Transaction, error) {
	return entities.CustomerTransactions(ctx, obj)
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context, id string) (*model.Customer, error) {
	return queries.Customer(ctx, id)
}

// Customer returns CustomerResolver implementation.
func (r *Resolver) Customer() CustomerResolver { return &customerResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type customerResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
