package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"customer-subgraph/graph/model"
)

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context, id string) (*model.Customer, error) {
	return &model.Customer{
		ID: id,
		Transactions: []*model.Transaction{
			{
				CustomerID: id,
				Bets: []*model.Bet{
					{
						ID:     "bet_001",
						Amount: 120.50,
						Game:   &model.Game{ID: "game_777"},
					},
					{
						ID:     "bet_002",
						Amount: 45.00,
						Game:   &model.Game{ID: "game_888"},
					},
				},
			},
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
