package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"game-subgraph/graph/model"
)

// FindGameByID is the resolver for the findGameByID field.
func (r *entityResolver) FindGameByID(ctx context.Context, id string) (*model.Game, error) {
	var name string
	var marketTypeID string

	switch id {
	case "game_777":
		name = "Championship Basketball Finals"
		marketTypeID = "mt_point_spread"
	case "game_888":
		name = "World Cup Tennis Open"
		marketTypeID = "mt_match_winner"
	default:
		name = "Generic Sporting Event"
		marketTypeID = "mt_standard"
	}

	return &model.Game{
		ID:           id,
		Name:         name,
		MarketTypeID: marketTypeID,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
