package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"game-subgraph/graph/model"
	"game-subgraph/resolvers/entities"
)

// FindGameByID is the resolver for the findGameByID field.
func (r *entityResolver) FindGameByID(ctx context.Context, id string) (*model.Game, error) {
	return entities.FindGameByID(ctx, id)
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
