// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bet struct {
	ID     string  `json:"id"`
	Game   *Game   `json:"game"`
	Amount float64 `json:"amount"`
}

func (Customer) IsEntity() {}

type Game struct {
	ID string `json:"id"`
}

func (Game) IsEntity() {}

type Query struct {
}

type Transaction struct {
	CustomerID string `json:"customerID"`
	Bets       []*Bet `json:"bets"`
}
